bind-addr: 0.0.0.0:7002
auth: password
password: 035715900Codeserver
cert: false
#cert: /home/mahdy/.local/share/code-server/192.168.1.27+1.pem
#cert-key: /home/mahdy/.local/share/code-server/192.168.1.27+1-key.pem
user-data-dir: /home/mahdy/.config/VSCodium/
extensions-dir: /home/mahdy/.vscode-oss/extensions/
